### ISSUE TITLE
support for video ?

### ISSUE THREAD

**Issue by Zecx** [nondanee/weiboPicDownloader#18]

**Comment by nondanee** [comment]
try it yourself first 😀

**Comment by Zecx** [comment]
btw, can u change readme.md with english language ?

**Comment by nondanee** [comment]
with pleasure 😀
is there some arguments that you can't understand after run with `-h` ?

**Comment by Zecx** [comment]
how about this?


![image](https://user-images.githubusercontent.com/37705250/39894362-c91a1a34-54d0-11e8-998c-070b9bd132cb.png)

**Comment by kybom** [comment]
```
root@xxx:~/weiboPicDownloader# python weiboPicDownloader.py -u 5751093744
1/1 Fri May 11 09:44:20 2018
Rakusaki 5751093744
finish analysis 0/0
practically get 0 weibos, 0 pictures
------------------------------
bye bye

```

**Comment by nondanee** [comment]
well, remove the prefix `100505`
weibo's uid is 10 digit number

Showing `5751093744 is a unvalid account` might be caused by network timeout
rerun and check again

**Comment by Zecx** [comment]
i think isn't about my connection, was trying with other username/id, and it's work 

![image](https://user-images.githubusercontent.com/37705250/40131143-5a81727e-5963-11e8-8f6f-ac86cda835e7.png)

**Comment by nondanee** [comment]
i just say that wrong invalid check caused by a temporary timeout which is a normal appearance for web crawler.
as for the weibo account whose id is 5751093744,
i had already checked its home page
**no weibo was post**
![screenshot_20180517-225657](https://user-images.githubusercontent.com/26399680/40186197-1b68791a-5a27-11e8-987b-e8f3059aab43.jpg)
of course program can't get any pictures to download
is there something wrong?

**Comment by Zecx** [comment]
sorry , i think -u in this section is username on weibo url like this

![image](https://user-images.githubusercontent.com/37705250/40208159-680840e4-5a62-11e8-83b9-d4d3366b826d.png)

**Comment by Zecx** [comment]
thanks for support, this project is awesome
